// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: encrypted_message.proto

#ifndef ENCRYPTED_MESSAGE_PB_H_
#define ENCRYPTED_MESSAGE_PB_H_

#include <stdint.h>
#include <string>
#include <pb.h> // Use nanopb if working with constrained devices

class EncryptedMessage {
public:
    EncryptedMessage();
    ~EncryptedMessage();

    // Getters
    int32_t id() const;
    std::string text() const;

    // Setters
    void set_id(int32_t value);
    void set_text(const std::string &value);

    // Serialization and Deserialization
    bool SerializeToArray(uint8_t* buffer, size_t size) const;
    bool ParseFromArray(const uint8_t* buffer, size_t size);

private:
    int32_t myId;
    std::string myText;
};

#endif  // ENCRYPTED_MESSAGE_PB_H_
